In [13]:
# This script contains exercises on 
# manipulating arrays with numpy
import numpy as np
x = np.arange(0, 3**3)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


#### 1. What is the length of x?

In [4]:
# Your code here
length = len(x)
print(length)

27


#### 2. How do you get the first value out of x?

In [6]:
# Your code here
first_value = x[0]
print(first_value)

0


#### 3. How do you get the last value out of x?

In [8]:
# Your code here
last_value = x[-1]
print(last_value)

26


#### 4. How do you get the first 5 values out of x?

In [11]:
# Your code here
first_five = x[:5]
print(first_five)

[0 1 2 3 4]


#### 5. What about the last 5 values of x?

In [18]:
# Your code here
last_five = x[-5:]
print(last_five)

[22 23 24 25 26]


#### 6. How do you get every other value out of x?

In [20]:
# Your code here
every_other = x[::2]
print(every_other)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26]



#### 7. Get the first 9 values of x, and reshape them to a 3x3 matrix. Assign this matrix to the variable `y`

In [25]:
# Your code here
first_nine = x[:9]
print(first_nine)
y = first_nine.reshape(3,3)
print(y)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. How do you get the middle value out of y?

In [27]:
y = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
])
# Your code here
y_middle = y[1,1]
print(y_middle)

4


#### 9. How do you get the first row out of y?

In [31]:
# Your code here
y_firstrow = y[0,:]
print(y_firstrow)

[0 1 2]


#### 10. How do you get the first column out of y?

In [32]:
# Your code here
y_firstcolumn = y[:,0]
print(y_firstcolumn)

[0 3 6]


#### 11. Reshape x into a 3x3x3 cube. Assign this to the variable `z`

In [34]:
x = np.arange(0, 3**3)
z = x.reshape(3,3,3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#### 12. How do you get the "center" value from z?

In [36]:
z = np.array([
    [[ 0, 1, 2],
     [ 3, 4, 5],
     [ 6, 7, 8]],
    [[ 9,10,11],
     [12,13,14],
     [15,16,17]],
    [[18,19,20],
     [21,22,23],
     [24,25,26]]
])
# Your code here
z_center = z[1,1,1]
print(z_center)

13



#### 13. How do you take the total sum of z?

In [39]:
# Your code here
z_sum = np.sum(z)
print(z_sum)

351



#### 14. How do you take the sum along the first dimension of z?

In [41]:
# Your code here
z_1D_sum = np.sum(z,axis=0)
print(z)
print(z_1D_sum)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[27 30 33]
 [36 39 42]
 [45 48 51]]


#### 15. How do you take the sum along the last dimension of z?

In [42]:
# Your code here
z_lastD_sum = np.sum(z,axis=2)
print(z_lastD_sum)

[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
